version: '3.7'
services:
  todo-web-application:
    image: prassyk/booking-service:0.0.1-SNAPSHOT
    container_name: booking-service
    ports:
      - "8082:8082"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: book
      RDS_USERNAME: book
      RDS_PASSWORD: dummybook
    networks:
      - booking-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword 
      MYSQL_USER: book
      MYSQL_PASSWORD: dummybook
      MYSQL_DATABASE: book
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - booking-network  
  
# Volumes
#volumes:
#  mysql-database-data-volume:
volumes:
  mysql-database-data-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:/voldata'  

networks:
  booking-network: